# SPDX-License-Identifier: MPL-2.0
repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
-   repo: local
    hooks:
    -   id: ensure-spdx-headers
        name: Ensure SPDX headers
        entry: python tools/add_spdx_headers.py
        language: system
        pass_filenames: true
